spring:
  cloud:
    vault:
      token: ${VAULT_TOKEN:hvs.SVdPkfnqHi6xqOZHaAcbURp4}
      scheme: http
      kv:
        enabled: true
  config:
    import: vault://
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54320/webid}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:tahamr08@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: we-bid


server:
  error:
    include-message: always
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        security: DEBUG
